using System.Text;

namespace Zendiator.SourceGenerator;

internal sealed partial class SourceEmitter
{
    private readonly GenerationModel _model;
    internal SourceEmitter(GenerationModel model)
    {
        _model = model;
    }

    private static StringBuilder CreateSourceBuilder() => new StringBuilder().AppendLine("""
        // <auto-generated/>
        #nullable enable
        """);
    internal string Emit()
    {
        var b = CreateSourceBuilder();
        b.AppendLine("""using global::Microsoft.Extensions.DependencyInjection;""");
        if (_model.Target.Namespace != null)
            b.AppendLine($$"""namespace {{_model.Target.Namespace}};""");
        EmitInterface(b);
        b.AppendLine("""
            /// <summary>Generated mediator with lazily captured dependencies.</summary>
            public sealed partial class Zendiator : IZendiator, global::System.IDisposable
            {
                private readonly global::Zendiator.DependencyInjection.ZendiatorServiceResolver _services;
                /// <summary>Creates a mediator bound to the supplied scope.</summary>
                public Zendiator(global::System.IServiceProvider services)
                {
                    global::System.ArgumentNullException.ThrowIfNull(services);
                    _services = new global::Zendiator.DependencyInjection.ZendiatorServiceResolver(services);
                }
                void global::System.IDisposable.Dispose() => _services.Dispose();
            """);
        EmitRequests(b);
        EmitNotifications(b);
        EmitMulti(b);
        EmitSyncRoutes(b);
        EmitSyncMulti(b);
        EmitStreams(b);
        EmitStreamTokenMerge(b);
        b.AppendLine("""}""");
        EmitRegistration(b);
        return b.ToString();
    }
}
