using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Zendiator.SourceGenerator;

internal sealed partial class SourceEmitter
{
    private readonly GenerationModel _model;
    private readonly string? _singleServiceTypeName;
    private readonly Dictionary<string, DependencySet> _dependencySets;
    private string MediatorServices => _model.Target.InheritServiceResolver ? "this" : "_services";
    internal SourceEmitter(GenerationModel model)
    {
        _model = model;
        _singleServiceTypeName = SingleServiceTypeName(model);
        _dependencySets = PlanDependencySets(model, _singleServiceTypeName != null);
    }

    private static string? SingleServiceTypeName(GenerationModel model)
    {
        var routes = model.Routes;
        if (!model.Target.InheritServiceResolver || (routes.Requests.Single.Count == 0 && routes.Synchronous.Single.Count == 0)
            || routes.Requests.Multiple.Count != 0
            || routes.Synchronous.Multiple.Count != 0 || routes.Notifications.Count != 0 || routes.Streams.Count != 0)
            return null;
        var handler = routes.Requests.Single.Count != 0 ? routes.Requests.Single[0].Handler : routes.Synchronous.Single[0].Handler;
        // The generated public mediator cannot expose an internal type in its generic base.
        if (!handler.IsReferenceType || !handler.IsPublic) return null;
        foreach (var route in routes.Requests.Single)
            if (route.IsOpen || route.Behaviors.Count != 0 || route.Handler.Name != handler.Name)
                return null;
        foreach (var route in routes.Synchronous.Single)
            if (route.IsOpen || route.Behaviors.Count != 0 || route.Handler.Name != handler.Name)
                return null;
        return handler.Name;
    }

    // An async method records cancellation as canceled and other failures as faulted, as the replaced publish method did.
    private void EmitFaulted(StringBuilder b)
    {
        if (!_model.Routes.Notifications.Any(static n => n.Subscribers.Count == 1 && !n.IsOpen)) return;
        b.AppendLine("""
            #pragma warning disable CS1998
                private static async global::System.Threading.Tasks.ValueTask Faulted(global::System.Runtime.ExceptionServices.ExceptionDispatchInfo failure) => failure.Throw();
                private static async global::System.Threading.Tasks.ValueTask AwaitSingleSubscriberNotification(global::System.Threading.Tasks.ValueTask operation) => await operation.ConfigureAwait(false);
            #pragma warning restore CS1998
            """);
    }

    private int InitialPageCapacity()
    {
        var routes = AllRouteServices(_model);
        if (routes.Any(static route => route.IsOpen)) return 32;
        var owned = new HashSet<string>(_dependencySets.Values.SelectMany(static set => set.Types).Select(static type => type.Name), StringComparer.Ordinal);
        var slots = _dependencySets.Count + routes.SelectMany(static route => route.Types).Select(static type => type.Name)
            .Where(name => !owned.Contains(name)).Distinct(StringComparer.Ordinal).Count();
        return slots == 0 || slots >= 32 ? 32 : slots;
    }

    private static StringBuilder CreateSourceBuilder() => new StringBuilder().AppendLine("""
        // <auto-generated/>
        #nullable enable
        """);
    internal string Emit()
    {
        var b = CreateSourceBuilder();
        var capacity = _singleServiceTypeName is null ? InitialPageCapacity() : 32;
        var capacityArgument = capacity == 32 ? "" : ", " + capacity.ToString(System.Globalization.CultureInfo.InvariantCulture);
        b.AppendLine("""using global::Microsoft.Extensions.DependencyInjection;""");
        if (_model.Target.Namespace != null)
            b.AppendLine($$"""namespace {{_model.Target.Namespace}};""");
        EmitInterface(b);
        var resolverBase = _singleServiceTypeName is { } singleServiceTypeName
            ? $$"""global::Zendiator.DependencyInjection.ZendiatorSingleServiceResolver<{{singleServiceTypeName}}>, """
            : _model.Target.InheritServiceResolver ? "global::Zendiator.DependencyInjection.ZendiatorServiceResolver<Zendiator>, " : "";
        b.AppendLine($$"""
            /// <summary>Generated mediator with lazily captured dependencies.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("Zendiator.SourceGenerator", "0.3.0")]
            public sealed partial class Zendiator : {{resolverBase}}IZendiator
            {
            """);
        if (_model.Target.InheritServiceResolver)
            b.AppendLine($$"""
                    /// <summary>Creates a mediator bound to the supplied scope.</summary>
                    public Zendiator(global::System.IServiceProvider services)
                        : base(services ?? throw new global::System.ArgumentNullException(nameof(services)){{capacityArgument}})
                    {
                    }
                """);
        else
            b.AppendLine($$"""
                    private readonly global::Zendiator.DependencyInjection.ZendiatorServiceResolver<Zendiator> _services;
                    /// <summary>Creates a mediator bound to the supplied scope.</summary>
                    public Zendiator(global::System.IServiceProvider services)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(services);
                        _services = new global::Zendiator.DependencyInjection.ZendiatorServiceResolver<Zendiator>(services{{capacityArgument}});
                    }
                """);
        b.AppendLine("""
                // Keep the token's address out of the inlined dispatch path.
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
                private static void ThrowDispatchCancellation(global::System.Threading.CancellationToken cancellationToken) => cancellationToken.ThrowIfCancellationRequested();
            """);
        EmitRequests(b);
        if (_model.Routes.Requests.Multiple.Any(static route => !route.IsVoid)
            || _model.Routes.Synchronous.Multiple.Any(static route => !route.IsVoid))
            b.AppendLine("""
                    // A generic allocation also supports array-valued and nullable responses.
                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    private static T[] CreateResultArray<T>(int count) => new T[count];
                """);
        EmitNotifications(b);
        EmitMulti(b);
        EmitSyncRoutes(b);
        EmitSyncMulti(b);
        EmitStreams(b);
        EmitStreamTokenMerge(b);
        EmitFaulted(b);
        EmitDependencySets(b);
        b.AppendLine("""}""");
        EmitRegistration(b);
        return b.ToString();
    }
}
