using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using static Zendiator.SourceGenerator.SymbolUtilities;

namespace Zendiator.SourceGenerator;

internal static partial class SourceEmitter
{
    internal static string Emit(INamedTypeSymbol mediator, List<Route> routes, List<NotificationRoute> notifications, List<MultiRoute> multiRoutes, List<Route> syncRoutes, List<MultiRoute> syncMultiRoutes, List<Route> streamRoutes, INamedTypeSymbol handlerDefinition, INamedTypeSymbol behaviorDefinition, INamedTypeSymbol voidHandlerDefinition, INamedTypeSymbol voidBehaviorDefinition, INamedTypeSymbol notificationHandlerDefinition, INamedTypeSymbol syncHandlerDefinition, INamedTypeSymbol syncVoidHandlerDefinition, INamedTypeSymbol syncBehaviorDefinition, INamedTypeSymbol syncVoidBehaviorDefinition, INamedTypeSymbol streamHandlerDefinition, INamedTypeSymbol streamBehaviorDefinition)
    {
        var ns = mediator.ContainingNamespace.IsGlobalNamespace ? null : mediator.ContainingNamespace.ToDisplayString();
        var prefix = ns == null ? "global::" : "global::" + ns + ".";
        return EmitCore(ns, prefix, Name(mediator), routes, notifications, multiRoutes, syncRoutes, syncMultiRoutes, streamRoutes, handlerDefinition, behaviorDefinition, voidHandlerDefinition, voidBehaviorDefinition, notificationHandlerDefinition, syncHandlerDefinition, syncVoidHandlerDefinition, syncBehaviorDefinition, syncVoidBehaviorDefinition, streamHandlerDefinition, streamBehaviorDefinition, null);
    }

    internal static string EmitAssembly(string targetNamespace, List<Route> routes, List<NotificationRoute> notifications, List<MultiRoute> multiRoutes, List<Route> syncRoutes, List<MultiRoute> syncMultiRoutes, List<Route> streamRoutes, INamedTypeSymbol handlerDefinition, INamedTypeSymbol behaviorDefinition, INamedTypeSymbol voidHandlerDefinition, INamedTypeSymbol voidBehaviorDefinition, INamedTypeSymbol notificationHandlerDefinition, INamedTypeSymbol syncHandlerDefinition, INamedTypeSymbol syncVoidHandlerDefinition, INamedTypeSymbol syncBehaviorDefinition, INamedTypeSymbol syncVoidBehaviorDefinition, INamedTypeSymbol streamHandlerDefinition, INamedTypeSymbol streamBehaviorDefinition, DiEmitOptions? di) =>
        EmitCore(targetNamespace, "global::" + targetNamespace + ".", "global::" + targetNamespace + ".Zendiator", routes, notifications, multiRoutes, syncRoutes, syncMultiRoutes, streamRoutes, handlerDefinition, behaviorDefinition, voidHandlerDefinition, voidBehaviorDefinition, notificationHandlerDefinition, syncHandlerDefinition, syncVoidHandlerDefinition, syncBehaviorDefinition, syncVoidBehaviorDefinition, streamHandlerDefinition, streamBehaviorDefinition, di);

    private static string EmitCore(string? targetNamespace, string prefix, string mediatorName, List<Route> routes, List<NotificationRoute> notifications, List<MultiRoute> multiRoutes, List<Route> syncRoutes, List<MultiRoute> syncMultiRoutes, List<Route> streamRoutes, INamedTypeSymbol handlerDefinition, INamedTypeSymbol behaviorDefinition, INamedTypeSymbol voidHandlerDefinition, INamedTypeSymbol voidBehaviorDefinition, INamedTypeSymbol notificationHandlerDefinition, INamedTypeSymbol syncHandlerDefinition, INamedTypeSymbol syncVoidHandlerDefinition, INamedTypeSymbol syncBehaviorDefinition, INamedTypeSymbol syncVoidBehaviorDefinition, INamedTypeSymbol streamHandlerDefinition, INamedTypeSymbol streamBehaviorDefinition, DiEmitOptions? di)
    {
        var b = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        b.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        if (targetNamespace != null)
            b.Append("namespace ").Append(targetNamespace).AppendLine(";");
        b.AppendLine("/// <summary>Typed request dispatch for this composition.</summary>\npublic interface IZendiator\n{");
        foreach (var route in routes)
        {
            b.AppendLine("    /// <summary>Dispatches the request through its configured pipeline.</summary>");
            b.Append("    ").Append(Signature(route)).AppendLine(";");
        }
        foreach (var notification in notifications)
        {
            b.AppendLine("    /// <summary>Publishes the notification to subscribers in order.</summary>");
            b.Append("    ").Append(NotificationSignature(notification, publish: false)).AppendLine(";");
            b.Append("    ").Append(NotificationSignature(notification, publish: true)).AppendLine(";");
        }
        if (notifications.Any(static n => !n.IsOpen))
        {
            b.AppendLine("    /// <summary>Publishes a registered notification by its runtime type.</summary>");
            b.Append("    ").Append(ErasedSignature(publish: false)).AppendLine(";");
            b.Append("    ").Append(ErasedSignature(publish: true)).AppendLine(";");
        }
        foreach (var multi in multiRoutes)
        {
            b.AppendLine("    /// <summary>Dispatches the request to every handler in order.</summary>");
            b.Append("    ").Append(MultiSignature(multi)).AppendLine(";");
        }
        foreach (var sync in syncRoutes)
        {
            b.AppendLine("    /// <summary>Dispatches the request synchronously without retaining it.</summary>");
            b.Append("    ").Append(SyncSignature(sync)).AppendLine(";");
        }
        foreach (var sync in syncMultiRoutes)
        {
            b.AppendLine("    /// <summary>Dispatches the request to every handler in order, synchronously.</summary>");
            b.Append("    ").Append(SyncMultiSignature(sync)).AppendLine(";");
        }
        foreach (var stream in streamRoutes)
        {
            b.AppendLine("    /// <summary>Streams items for the request through its configured pipeline. Enumeration is lazy and scope-safe.</summary>");
            b.Append("    ").Append(StreamSignature(stream)).AppendLine(";");
        }
        b.AppendLine("}\n/// <summary>Generated scoped mediator.</summary>\npublic sealed partial class Zendiator : IZendiator\n{");
        b.AppendLine("    private readonly global::System.IServiceProvider _services;\n    /// <summary>Creates a mediator bound to the supplied scope.</summary>\n    public Zendiator(global::System.IServiceProvider services)\n    {\n        global::System.ArgumentNullException.ThrowIfNull(services);\n        _services = services;\n    }");
        // The container owns lifetime and reuse. A mutable IServiceCollection
        // cannot prove which descriptors a previously built provider captured.
        for (var index = 0; index < routes.Count; index++)
        {
            var route = routes[index];
            if (route.IsOpen)
            {
                EmitOpenRoute(b, route, index, handlerDefinition, behaviorDefinition, voidHandlerDefinition, voidBehaviorDefinition);
                continue;
            }
            b.AppendLine("    /// <summary>Dispatches the request through its configured pipeline.</summary>");
            b.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            b.Append("    public ").Append(Signature(route)).AppendLine("\n    {");
            if (route.Behaviors.Count == 0)
            {
                Guard(b, route, "        ");
                var direct = UseDirectCall(route.Handler, route.IsVoid ? voidHandlerDefinition : handlerDefinition);
                var receiver = $"_services.GetRequiredService<{Name(route.Handler)}>()";
                if (!direct) receiver = "((" + HandlerContract(route) + ")" + receiver + ")";
                b.Append("        return ").Append(receiver).AppendLine(".HandleAsync(request, cancellationToken);\n    }");
                continue;
            }
            b.Append("        return new Route").Append(index).AppendLine("Node0(_services).InvokeAsync(request, cancellationToken);\n    }");
            for (var node = 0; node <= route.Behaviors.Count; node++)
            {
                b.Append("    private readonly struct Route").Append(index).Append("Node").Append(node)
                    .Append("(global::System.IServiceProvider services) : ").Append(ContinuationContract(route)).AppendLine("\n    {");
                b.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                b.Append("        public ").Append(TaskContract(route)).Append(" InvokeAsync(").Append(Name(route.Request))
                    .AppendLine(" request, global::System.Threading.CancellationToken cancellationToken)\n        {");
                Guard(b, route, "            ");
                if (node == route.Behaviors.Count)
                {
                    if (UseDirectCall(route.Handler, route.IsVoid ? voidHandlerDefinition : handlerDefinition))
                        HandlerCallDirect(b, route);
                    else
                        HandlerCall(b, route, "services", "            ");
                }
                else
                {
                    var receiver = $"services.GetRequiredService<{Name(route.Behaviors[node])}>()";
                    if (!UseDirectCall(route.Behaviors[node], route.IsVoid ? voidBehaviorDefinition : behaviorDefinition))
                        receiver = "((" + BehaviorContract(route) + ")" + receiver + ")";
                    b.Append("            return ").Append(receiver).Append(".HandleAsync(request, new Route")
                        .Append(index).Append("Node").Append(node + 1).AppendLine("(services), cancellationToken);");
                }
                b.AppendLine("        }\n    }");
            }
        }
        EmitNotifications(b, notifications, notificationHandlerDefinition);
        EmitMulti(b, multiRoutes, handlerDefinition, behaviorDefinition, voidHandlerDefinition, voidBehaviorDefinition);
        EmitSyncRoutes(b, syncRoutes, syncHandlerDefinition, syncVoidHandlerDefinition, syncBehaviorDefinition, syncVoidBehaviorDefinition);
        EmitSyncMulti(b, syncMultiRoutes, syncHandlerDefinition, syncVoidHandlerDefinition, syncBehaviorDefinition, syncVoidBehaviorDefinition);
        EmitStreams(b, streamRoutes, streamHandlerDefinition, streamBehaviorDefinition);
        // Shared token-merge helper: link only when both tokens are cancellable and different.
        if (streamRoutes.Count != 0)
        {
            b.AppendLine("    private static global::System.Threading.CancellationToken MergeStreamTokens(global::System.Threading.CancellationToken apiToken, global::System.Threading.CancellationToken enumeratorToken, out global::System.Threading.CancellationTokenSource? linked)");
            b.AppendLine("    {");
            b.AppendLine("        linked = null;");
            b.AppendLine("        if (!apiToken.CanBeCanceled) return enumeratorToken;");
            b.AppendLine("        if (!enumeratorToken.CanBeCanceled) return apiToken;");
            b.AppendLine("        if (apiToken.Equals(enumeratorToken)) return apiToken;");
            b.AppendLine("        linked = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(apiToken, enumeratorToken);");
            b.AppendLine("        return linked.Token;");
            b.AppendLine("    }");
        }
        b.AppendLine("}");
        if (di == null || di.EmitExtensions)
        {
            b.AppendLine("/// <summary>Registers the generated mediator and its concrete services.</summary>\npublic static class ZendiatorServiceCollectionExtensions\n{");
            b.AppendLine("    /// <summary>Adds scoped defaults without replacing existing registrations.</summary>\n    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZendiator(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)\n    {\n        global::System.ArgumentNullException.ThrowIfNull(services);\n        return AddZendiator(services, global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped);\n    }");
            b.AppendLine("    /// <summary>Adds defaults with the selected lifetime without replacing existing registrations. All registrations share the lifetime.</summary>\n    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZendiator(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime)\n    {\n        global::System.ArgumentNullException.ThrowIfNull(services);\n        if (lifetime is not (global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton or global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped or global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient))\n            throw new global::System.ArgumentOutOfRangeException(nameof(lifetime), lifetime, null);");
            EmitRegistrationEntries(b, prefix, mediatorName, routes, notifications, multiRoutes, syncRoutes, syncMultiRoutes, streamRoutes, "lifetime");
            b.AppendLine("        return services;\n    }\n}");
        }
        else
        {
            EmitRegistrar(b, prefix, mediatorName, routes, notifications, multiRoutes, syncRoutes, syncMultiRoutes, streamRoutes, di.Fingerprint);
        }
        return b.ToString();
    }
}
