using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using static Zendiator.SourceGenerator.SymbolUtilities;

namespace Zendiator.SourceGenerator;

internal static partial class SourceEmitter
{
    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    internal static string EmitInterceptorFile(List<(int Version, string Data, bool IsLambda, bool IsExtensionForm)> shims, string registrarPrefix)
    {
        if (shims.Count == 0) return "";
        var b = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        EmitShims(b, shims, registrarPrefix);
        return b.ToString();
    }

    private static void Register(StringBuilder b, string arguments, string lifetime)
    {
        b.Append("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(")
            .Append(arguments).Append(", ").Append(lifetime).AppendLine("));");
    }

    private static void EmitRegistrationEntries(StringBuilder b, string prefix, string mediatorName, List<Route> routes, List<NotificationRoute> notifications, List<MultiRoute> multiRoutes, List<Route> syncRoutes, List<MultiRoute> syncMultiRoutes, List<Route> streamRoutes, string lifetime)
    {
        var mediatorNameLocal = mediatorName;
        Register(b, $"typeof({mediatorNameLocal}), typeof({mediatorNameLocal})", lifetime);
        b.Append("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(typeof(")
            .Append(prefix).Append("IZendiator), static provider => (object)provider.GetRequiredService<").Append(mediatorName).Append(">(), ").Append(lifetime).AppendLine("));");
        foreach (var service in routes.SelectMany(r => r.Behaviors.Concat(new[] { r.Handler }).Select(s => (Route: r, Service: s)))
            .Select(p => p.Route.IsOpen ? $"typeof({OpenTypeofName(p.Service)}), typeof({OpenTypeofName(p.Service)})" : $"typeof({Name(p.Service)}), typeof({Name(p.Service)})")
            .Distinct().OrderBy(n => n, StringComparer.Ordinal))
            Register(b, service, lifetime);
        var notificationServices = new List<string>();
        foreach (var notification in notifications)
        {
            if (notification.IsOpen)
            {
                foreach (var sub in notification.Subscribers)
                    notificationServices.Add($"typeof({OpenTypeofName(sub.Handler)}), typeof({OpenTypeofName(sub.Handler)})");
            }
            else
            {
                foreach (var sub in notification.Subscribers)
                    notificationServices.Add($"typeof({Name(sub.Handler)}), typeof({Name(sub.Handler)})");
            }
        }
        foreach (var service in notificationServices.Distinct().OrderBy(n => n, StringComparer.Ordinal))
            Register(b, service, lifetime);
        var multiServices = new List<string>();
        foreach (var multi in multiRoutes)
        {
            foreach (var branch in multi.Branches)
            {
                multiServices.Add(branch.HandlerIsOpen
                    ? $"typeof({OpenTypeofName(branch.Handler)}), typeof({OpenTypeofName(branch.Handler)})"
                    : $"typeof({Name(branch.Handler)}), typeof({Name(branch.Handler)})");
                foreach (var behavior in branch.Behaviors)
                {
                    multiServices.Add(multi.IsOpen
                        ? $"typeof({OpenTypeofName(behavior)}), typeof({OpenTypeofName(behavior)})"
                        : $"typeof({Name(behavior)}), typeof({Name(behavior)})");
                }
            }
        }
        foreach (var service in multiServices.Distinct().OrderBy(n => n, StringComparer.Ordinal))
            Register(b, service, lifetime);
        var syncServices = new List<string>();
        foreach (var route in syncRoutes)
        {
            foreach (var behavior in route.Behaviors)
            {
                syncServices.Add(route.IsOpen
                    ? $"typeof({OpenTypeofName(behavior)}), typeof({OpenTypeofName(behavior)})"
                    : $"typeof({Name(behavior)}), typeof({Name(behavior)})");
            }
            syncServices.Add(route.IsOpen
                ? $"typeof({OpenTypeofName(route.Handler)}), typeof({OpenTypeofName(route.Handler)})"
                : $"typeof({Name(route.Handler)}), typeof({Name(route.Handler)})");
        }
        foreach (var multi in syncMultiRoutes)
        {
            foreach (var branch in multi.Branches)
            {
                syncServices.Add(branch.HandlerIsOpen
                    ? $"typeof({OpenTypeofName(branch.Handler)}), typeof({OpenTypeofName(branch.Handler)})"
                    : $"typeof({Name(branch.Handler)}), typeof({Name(branch.Handler)})");
                foreach (var behavior in branch.Behaviors)
                {
                    syncServices.Add(multi.IsOpen
                        ? $"typeof({OpenTypeofName(behavior)}), typeof({OpenTypeofName(behavior)})"
                        : $"typeof({Name(behavior)}), typeof({Name(behavior)})");
                }
            }
        }
        foreach (var service in syncServices.Distinct().OrderBy(n => n, StringComparer.Ordinal))
            Register(b, service, lifetime);
        var streamServices = new List<string>();
        foreach (var route in streamRoutes)
        {
            foreach (var behavior in route.Behaviors)
            {
                streamServices.Add(route.IsOpen
                    ? $"typeof({OpenTypeofName(behavior)}), typeof({OpenTypeofName(behavior)})"
                    : $"typeof({Name(behavior)}), typeof({Name(behavior)})");
            }
            streamServices.Add(route.IsOpen
                ? $"typeof({OpenTypeofName(route.Handler)}), typeof({OpenTypeofName(route.Handler)})"
                : $"typeof({Name(route.Handler)}), typeof({Name(route.Handler)})");
        }
        foreach (var service in streamServices.Distinct().OrderBy(n => n, StringComparer.Ordinal))
            Register(b, service, lifetime);
    }

    private static void EmitRegistrar(StringBuilder b, string prefix, string mediatorName, List<Route> routes, List<NotificationRoute> notifications, List<MultiRoute> multiRoutes, List<Route> syncRoutes, List<MultiRoute> syncMultiRoutes, List<Route> streamRoutes, string fingerprint)
    {
        b.AppendLine("/// <summary>Generated DI registrar. Prefer AddZendiator; do not call directly.</summary>");
        b.AppendLine("internal static class ZendiatorGeneratedRegistrar");
        b.AppendLine("{");
        b.Append("    internal const string StructureFingerprint = \"").Append(EscapeString(fingerprint)).AppendLine("\";");
        b.AppendLine("    internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Zendiator.DependencyInjection.ZendiatorConfigurationSnapshot snapshot)");
        b.AppendLine("    {");
        b.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        b.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(snapshot);");
        b.AppendLine("        if (snapshot.GetFingerprint() != StructureFingerprint)");
        b.AppendLine("            throw new global::System.InvalidOperationException(\"AddZendiator configuration does not match the generated structure. Keep one configuration per compilation.\");");
        EmitRegistrationEntries(b, prefix, mediatorName, routes, notifications, multiRoutes, syncRoutes, syncMultiRoutes, streamRoutes, "snapshot.ServiceLifetime");
        b.AppendLine("        return services;");
        b.AppendLine("    }");
        b.AppendLine("}");
    }

    private static void EmitShims(StringBuilder b, List<(int Version, string Data, bool IsLambda, bool IsExtensionForm)> shims, string registrarPrefix)
    {
        b.AppendLine("namespace System.Runtime.CompilerServices");
        b.AppendLine("{");
        b.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]");
        b.AppendLine("    file sealed class InterceptsLocationAttribute : System.Attribute");
        b.AppendLine("    {");
        b.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        b.AppendLine("    }");
        b.AppendLine("}");
        b.AppendLine("namespace Zendiator.Generated.Interceptors");
        b.AppendLine("{");
        b.AppendLine("    static class AddZendiatorShims");
        b.AppendLine("    {");
        var index = 0;
        foreach (var (version, data, isLambda, isExtensionForm) in shims)
        {
            var name = "Shim" + index++;
            var receiver = isExtensionForm ? "this " : "";
            b.Append("        [System.Runtime.CompilerServices.InterceptsLocation(").Append(version).Append(", \"").Append(EscapeString(data)).AppendLine("\")]");
            if (isLambda)
            {
                b.Append("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ").Append(name).Append("(").Append(receiver).AppendLine("global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.Action<global::Zendiator.DependencyInjection.ZendiatorConfiguration>? configure)");
                b.AppendLine("        {");
                b.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(configure);");
                b.AppendLine("            var configuration = new global::Zendiator.DependencyInjection.ZendiatorConfiguration();");
                b.AppendLine("            configure(configuration);");
                b.Append("            return ").Append(registrarPrefix).AppendLine("ZendiatorGeneratedRegistrar.Add(services, configuration.Snapshot());");
                b.AppendLine("        }");
            }
            else
            {
                b.Append("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ").Append(name).Append("(").Append(receiver).AppendLine("global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
                b.AppendLine("        {");
                b.AppendLine("            var configuration = new global::Zendiator.DependencyInjection.ZendiatorConfiguration();");
                b.Append("            return ").Append(registrarPrefix).AppendLine("ZendiatorGeneratedRegistrar.Add(services, configuration.Snapshot());");
                b.AppendLine("        }");
            }
        }
        b.AppendLine("    }");
        b.AppendLine("}");
    }
}
